# Generated by Django 4.2.7 on 2023-11-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastralrequest',
            name='status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
